### ISSUE TITLE
Pip not able to install climetlab (v0.11.31) in windows with Python 3.7 : HDF5 headers not found

### ISSUE THREAD

**Issue by jodemaey** [ecmwf/climetlab#41]
The title is quite explicit :p . I get this error in the tests for the release of a new version of the [EUMETNET benchmark climetlab](https://github.com/Climdyn/climetlab-eumetnet-postprocessing-benchmark) plugin. Is climetlab still supported in Python 3.7?

See the error log here:
```
Collecting climetlab
  Downloading climetlab-0.11.31.tar.gz (128 kB)
     -------------------------------------- 128.1/128.1 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy
  Downloading numpy-1.21.6-cp37-cp37m-win_amd64.whl (14.0 MB)
     --------------------------------------- 14.0/14.0 MB 46.7 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-win_amd64.whl (10.0 MB)
     --------------------------------------- 10.0/10.0 MB 57.9 MB/s eta 0:00:00
Collecting xarray>=0.19.0
  Downloading xarray-0.20.2-py3-none-any.whl (845 kB)
     ------------------------------------- 845.2/845.2 kB 26.9 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.8/62.8 kB 3.3 MB/s eta 0:00:00
Collecting dask
  Downloading dask-2022.2.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 22.2 MB/s eta 0:00:00
Collecting netcdf4
  Downloading netCDF4-1.6.0.tar.gz (774 kB)
     ------------------------------------- 774.2/774.2 kB 24.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [25 lines of output]
  reading from setup.cfg...
  
      HDF5_DIR environment variable not set, checking some standard locations ..
  checking C:\Users\runneradmin\include ...
  hdf5 headers not found in C:\Users\runneradmin\include
  checking /usr/local\include ...
  hdf5 headers not found in /usr/local\include
  checking /sw\include ...
  hdf5 headers not found in /sw\include
  checking /opt\include ...
  hdf5 headers not found in /opt\include
  checking /opt/local\include ...
  hdf5 headers not found in /opt/local\include
  checking /opt/homebrew\include ...
  hdf5 headers not found in /opt/homebrew\include
  checking /usr\include ...
  hdf5 headers not found in /usr\include
  Traceback (most recent call last):
    File "<string>", line 36, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-wpzd3q9h\netcdf4_0e84f88a843e43dab815c3ef9955b375\setup.py", line 444, in <module>
      _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-wpzd3q9h\netcdf4_0e84f88a843e43dab815c3ef9955b375\setup.py", line 385, in _populate_hdf5_info
Error:       raise ValueError('did not find HDF5 headers')
  ValueError: did not find HDF5 headers
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

**Comment by jodemaey** [comment]
This seems to be a common problem with NetCDF4 after a new release on Python 3.7:

https://github.com/Unidata/netcdf4-python/issues/901#issue-425297888

https://github.com/Unidata/netcdf4-python/issues/1031#issue-665205433

**Comment by floriankrb** [comment]
Indeed, apparently, the issue comes from the netcdf4 package, there is not much that we can do from climetlab.

**Comment by jodemaey** [comment]
I want to comment on the fact that this is painful for plugin maintainers, because I cannot push to pip server due to this.
Plugin users start complaining that they cannot reach latest features because pip and github are not aligned.
If I have to wait 6 months that this is solved for this very particular version, then this is a problem.
The solution I see is dropping some Python versions in the tests to publish. 

@floriankrb :
What would be the best according to you : 

- Drop all Windows tests (problems are usually there)
- Drop only Python 3.7 Windows tests

?

Thank you in advance.

**Comment by floriankrb** [comment]
Yes, droping support for Windows python 3.7 would make sense IMO, depending on your users of course.

You can achieve this in the .github/workflow yaml file using `exclude` as in:
```
    strategy:
      fail-fast: true
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - platform: "windows-latest"
            python-version: "3.7"
```

**Comment by jodemaey** [comment]
Ok, I will do that. I hope this is not a slippery slope though :-)
