### ISSUE TITLE
Is climetlab still supported on Python 3.7

### ISSUE THREAD

**Issue by jodemaey** [ecmwf/climetlab#44]
Hi there,

I maintain a plugin and all my Python 3.7 workflows fail at the moment, whatever the OS used.
Here is an example:

```
Collecting climetlab
  Downloading climetlab-0.12.6.tar.gz (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.5/149.5 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3gji2bae/climetlab_83cb018ea656414aaac7ca81d54e30a1/setup.py", line 43, in <module>
          + " is not supported. Python 3.8 is required."
      Exception: Python version sys.version_info(major=3, minor=7, micro=15, releaselevel='final', serial=0) is not supported. Python 3.8 is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

So did Python 3.7 support for climetlab dropped? I would like to know because then I need to drop it for my plugin too.

Thank you in advance,

Jonathan

**Comment by floriankrb** [comment]
No, python 3.7 is not supported by numpy anymore, so we dropped support for python 3.7 too.

**Comment by jodemaey** [comment]
You should drop the flag in pip then, because it is misleading.
